site_name: RPI Smart Mirror User Documentation
site_url: https://sitename.example
theme:
  name: material
  font:
    text: Roboto
    code: Red Hat Mono
<<<<<<< HEAD
  features:
    - content.code.copy
    - content.code.annotate
=======
  icon:
    logo: fontawesome/solid/w
>>>>>>> b78231b6fde1c8091ab69a170401c6c173ceb41b
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
<<<<<<< HEAD

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
=======
  # palette:
  # scheme: slate
  # primary: red
  # accent: purple
markdown_extensions:
  - attr_list
  - pydownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
  
>>>>>>> b78231b6fde1c8091ab69a170401c6c173ceb41b

  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true